# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #(1..2).each do |i|
    config.vm.define "redisMaster" do |node|
      node.vm.hostname = "redisMaster"
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "192.168.33.11"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "redisMaster"
        vb.gui = false
        vb.memory = "2046"
      end

      #node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    end
  #end


  (2..3).each do |i|
    config.vm.define "redisSlave#{i}" do |node|
      node.vm.hostname = "redisSlave#{i}"
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "Qualcomm Atheros QCA9377 Wireless Network Adapter"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "redisSlave#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      #node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    end
  end
end